version: 2.1

orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@3.4.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      #- run:
      #    command: ./manage.py test
      #    name: Test
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install pytest-cov
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml
      - run:
          name: run test-cov
          command: |
            . venv/bin/activate
            pytest --cov=src
      - slack/notify:
          channel: my-circleci
          color: '#42e2f4'
          mentions: 'yuji-k64613'
          message: CircleCI1からの通知
          webhook: https://hooks.slack.com/services/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

workflows:
  main:
    jobs:
      - build-and-test
